/**
 * Generated Playwright Test
 * Source Execution: exec_1768315762
 * Generated: 2026-01-13 14:52:41 UTC
 * Status: completed
 * 
 * Story:
 * Step 1: Go to https://hub-stage.datacommons.cancer.gov/
 * Step 1 a: Wait 3 seconds
 * Step 2: If there is a Continue button click on that.
 * Step 3: Click on link Login .(https://hub-stage.datacommons.cancer.gov/)
 * Step 4: Click On Login.gov button.
 * Step 5: Enter Username as Laxmi_AI_test@yahoo.com
 * Step 6: Enter Password as Testnci123456789!
 * Step 7: Click Submit Button
 * Step 8: Enter the TOTP/authenticator code in the one-time code input field. Use browser_fill tool. The TOTP code will be automatically generated by the system.
 * Step 9: Wait 5 seconds
 * Step 10: Click Submit button to submit the TOTP code
 * Step 11: Handle 2FA reminder (if appears)
 * Step 12: click on the button with text "Grant"(if appears)
 * Step 13: Verify successful login
 * Step 14: click on "Data Submissions" link , it goes to https://hub-stage.datacommons.cancer.gov/data-submissions
 * Step 15: On Data submission page click on button called "Create a Data Submission"
 */

import { test, expect } from '@playwright/test';
import * as fs from 'fs';
import * as path from 'path';
import { URL } from 'url';

// Load environment variables from .env file (for TOTP_SECRET_KEY, etc.)
// Check multiple locations: same dir, parent, home, or 3 levels up
let envFile: string | null = null;
try {
  const dotenv = require('dotenv');
  const testFileDir = __dirname;
  const possibleEnvLocations = [
    path.join(testFileDir, '.env'),  // Same directory as test file
    path.join(path.dirname(testFileDir), '.env'),  // Parent directory
    path.join(require('os').homedir(), '.env'),  // Home directory
    path.join(path.dirname(path.dirname(path.dirname(testFileDir))), '.env'),  // 3 levels up
  ];
  
  for (const loc of possibleEnvLocations) {
    if (fs.existsSync(loc)) {
      envFile = loc;
      dotenv.config({ path: loc });
      console.log(`✅ Loaded environment variables from ${envFile}`);
      break;
    }
  }
  
  if (!envFile) {
    console.log(`⚠️  .env file not found. Checked locations:`);
    for (const loc of possibleEnvLocations) {
      console.log(`   - ${loc}`);
    }
    console.log(`   Please create a .env file with TOTP_SECRET_KEY=your_secret_key`);
  }
} catch (e: any) {
  if (e.code === 'MODULE_NOT_FOUND') {
    console.log("⚠️  dotenv not installed - environment variables must be set manually");
  } else {
    console.log(`⚠️  Failed to load .env file: ${e}`);
  }
}

// ============================================================================
// TEST-SPECIFIC VALUES (from story - embedded in test, not in registry)
// ============================================================================

// ============================================================================
// MULTI-REGISTRY SUPPORT (loads all registries for pages visited in test)
// ============================================================================
// Automatically detects and loads all registry files needed based on URLs visited
// Update paths below if registries are in different locations
const REGISTRY_PATHS = [
  'LoginMFA.aspx_page.json',
  'hub-stage.datacommons.cancer.gov/data-submissions_page.json',
  'hub-stage.datacommons.cancer.gov/home_page.json',
  'secure.login.gov/authenticator_page.json',
  'secure.login.gov/home_page.json',
  'sts.nih.gov/consent_page.json',
];

// Load registries per domain/page (for dynamic loading based on current page)
// NO MERGE: Keep registries separate to avoid conflicts when same element name exists in multiple registries
const REGISTRIES_BY_PATH: { [key: string]: any } = {};  // registry_path -> registry_data
let loadedCount = 0;

for (const registryPathStr of REGISTRY_PATHS) {
  try {
    if (fs.existsSync(registryPathStr)) {
      const registryData = JSON.parse(fs.readFileSync(registryPathStr, 'utf-8'));
      // Store per-path for dynamic loading (NO MERGE - prevents conflicts)
      REGISTRIES_BY_PATH[registryPathStr] = registryData;
      loadedCount++;
      console.log(`✅ Loaded registry: ${Object.keys(registryData.elements || {}).length} elements from ${path.basename(registryPathStr)}`);
    } else {
      console.log(`⚠️  Registry file not found: ${registryPathStr}`);
    }
  } catch (e: any) {
    console.log(`⚠️  Failed to load registry ${registryPathStr}: ${e}`);
  }
}

if (loadedCount > 0) {
  const totalElements = Object.values(REGISTRIES_BY_PATH).reduce((sum: number, reg: any) => sum + Object.keys(reg.elements || {}).length, 0);
  const totalIds = Object.values(REGISTRIES_BY_PATH).reduce((sum: number, reg: any) => sum + Object.keys(reg.id_index || {}).length, 0);
  console.log(`✅ Loaded ${loadedCount} registries: ${totalElements} total elements, ${totalIds} total IDs (separate, not merged)`);
}

function getRegistryForPage(pageUrl: string | null): any {
  /**Get registry for current page based on URL*/
  if (!pageUrl) {
    return null;
  }
  
  const parsed = new URL(pageUrl);
  const domain = parsed.hostname.split(':')[0];  // Remove port if present
  
  // Extract page name from URL path
  const pathParts = parsed.pathname.split('/').filter(p => p);
  let pageName: string;
  if (pathParts.length === 0) {
    pageName = 'home';
  } else if (pathParts[pathParts.length - 1] === 'explore') {
    pageName = 'explore';
  } else {
    // Get last path segment, remove query params
    pageName = pathParts[pathParts.length - 1].split('?')[0].split('#')[0];
    // Remove file extension if present
    if (pageName.includes('.')) {
      pageName = pageName.split('.').slice(0, -1).join('.');
    }
  }
  
  // Try to find matching registry file
  let bestMatch: any = null;
  let bestScore = 0;
  
  for (const [registryPathStr, registryData] of Object.entries(REGISTRIES_BY_PATH)) {
    // Check if registry path matches domain
    if (!registryPathStr.includes(domain)) {
      continue;
    }
    
    let score = 0;
    // Score based on how well the registry path matches the page
    
    // Exact page name match gets highest score
    if (registryPathStr.includes(pageName)) {
      score += 10;
    }
    
    // Check for specific page patterns in registry path
    const registryFilename = registryPathStr.split('/').pop() || '';
    
    // Match page name in filename (e.g., LoginMFA.aspx_page.json for LoginMFA.aspx)
    if (registryFilename.toLowerCase().includes(pageName.toLowerCase())) {
      score += 8;
    }
    
    // Match common patterns
    if (registryFilename.toLowerCase().includes('home') && (pathParts.length === 0 || pathParts[pathParts.length - 1] === '')) {
      score += 5;
    }
    
    // Match domain exactly
    if (registryPathStr.includes(domain)) {
      score += 3;
    }
    
    if (score > bestScore) {
      bestScore = score;
      bestMatch = registryData;
    }
  }
  
  // If we found a good match, return it
  if (bestMatch && bestScore >= 3) {
    return bestMatch;
  }
  
  // Fallback: return first registry that matches domain
  for (const [registryPathStr, registryData] of Object.entries(REGISTRIES_BY_PATH)) {
    if (registryPathStr.includes(domain)) {
      return registryData;
    }
  }
  
  return null;
}

function getXpathById(elementId: string, pageUrl?: string): string {
  /**Get XPath from registry by unique ID - prefers registry for current page, searches all registries for same domain if not found*/
  if (!elementId) {
    throw new Error(`❌ element_id is required`);
  }
  
  // STEP 1: Try to get registry for current page first
  if (pageUrl) {
    const pageRegistry = getRegistryForPage(pageUrl);
    if (pageRegistry) {
      const currentRegistry = pageRegistry.elements || {};
      const currentIdIndex = pageRegistry.id_index || {};
      
      // Check if element_id exists in current page registry
      if (elementId in currentIdIndex) {
        const registryKey = currentIdIndex[elementId];
        if (registryKey in currentRegistry) {
          const xpath = currentRegistry[registryKey].xpath;
          if (xpath) {
            return xpath;
          }
        }
      }
    }
  }
  
  // STEP 2: If not found in page-specific registry, search all registries for same domain
  if (pageUrl) {
    const parsed = new URL(pageUrl);
    const domain = parsed.hostname.split(':')[0];  // Remove port if present
    
    // Search all registries for this domain
    for (const [registryPathStr, registryData] of Object.entries(REGISTRIES_BY_PATH)) {
      if (registryPathStr.includes(domain)) {
        const idIndex = registryData.id_index || {};
        const elements = registryData.elements || {};
        
        if (elementId in idIndex) {
          const registryKey = idIndex[elementId];
          if (registryKey in elements) {
            const xpath = elements[registryKey].xpath;
            if (xpath) {
              return xpath;
            }
          }
        }
      }
    }
  }
  
  // STEP 3: Last resort - search ALL registries (cross-domain fallback)
  for (const registryData of Object.values(REGISTRIES_BY_PATH)) {
    const idIndex = registryData.id_index || {};
    const elements = registryData.elements || {};
    
    if (elementId in idIndex) {
      const registryKey = idIndex[elementId];
      if (registryKey in elements) {
        const xpath = elements[registryKey].xpath;
        if (xpath) {
          return xpath;
        }
      }
    }
  }
  
  // Not found in any registry
  throw new Error(`❌ element_id '${elementId}' not found in any registry id_index`);
}

test('test_step_https_stage', async ({ page }) => {
  /**Auto-generated test from AI discovery - 1:1 mirror of AI execution*/
  // Track critical failures (non-optional steps that failed)
  const criticalFailures: string[] = [];
  
  // Set viewport to match AI agent (tabs visible, not hidden in "More" dropdown)
  await page.setViewportSize({ width: 1920, height: 1080 });
  
  try {
    // Step 1: https://hub-stage.datacommons.cancer.gov/
    await page.waitForTimeout(3000);  // Wait 3 seconds before step
    try {
      await page.goto('https://hub-stage.datacommons.cancer.gov/');
      await page.waitForLoadState('networkidle');
      console.log('📍 Step 1: Navigated to https://hub-stage.datacommons.cancer.gov/');
      // Capture screenshot after navigation
      try {
        await page.screenshot({ path: 'storage/screenshots/pw_step1_navigate.png' });
        console.log('📸 Screenshot saved: storage/screenshots/pw_step1_navigate.png');
      } catch {
        // Ignore screenshot errors
      }
    } catch (e: any) {
      console.log(`❌ Step 1: Navigation failed: ${e}`);
      // Capture screenshot even on failure
      try {
        await page.screenshot({ path: 'storage/screenshots/pw_step1_navigate_failed.png' });
        console.log('📸 Screenshot saved: storage/screenshots/pw_step1_navigate_failed.png');
      } catch {
        // Ignore screenshot errors
      }
      // Continuing to next step despite failure (to capture screenshots)
    }
    
    // Step 1: Wait 3 seconds
    await page.waitForTimeout(3000);  // Wait 3 seconds before step
    try {
      await page.waitForTimeout(3000);
      console.log('⏱️  Step 1: Waited 3000ms');
      // Capture screenshot after wait
      try {
        await page.screenshot({ path: 'storage/screenshots/pw_step1_wait.png' });
        console.log('📸 Screenshot saved: storage/screenshots/pw_step1_wait.png');
      } catch {
        // Ignore screenshot errors
      }
    } catch (e: any) {
      console.log(`❌ Step 1: Wait failed: ${e}`);
      // Capture screenshot even on failure
      try {
        await page.screenshot({ path: 'storage/screenshots/pw_step1_wait_failed.png' });
        console.log('📸 Screenshot saved: storage/screenshots/pw_step1_wait_failed.png');
      } catch {
        // Ignore screenshot errors
      }
      // Continuing to next step despite failure (to capture screenshots)
    }
    
    // Step 2: If there is a Continue button click on that.
    await page.waitForTimeout(3000);  // Wait 3 seconds before step
    // Using element_id: ID_9e268d1f (PURE REGISTRY - XPath from JSON ONLY)
    const elementId2 = 'ID_9e268d1f';
    
    try {
      const xpath2 = getXpathById(elementId2, page.url());  // Lookup from JSON registry (prefers current page registry)
      const selector2 = `xpath=${xpath2}`;
      const element2 = page.locator(selector2).nth(0);
      await element2.waitFor({ state: 'visible', timeout: 10000 });
      await element2.click();
      await page.waitForTimeout(1000);  // Wait after click (matches AI behavior)
      // Wait for dialog to disappear (if popup was dismissed)
      try {
        // Wait for dialog to be detached (completely removed from DOM) - most reliable
        await page.locator('[data-testid="system-use-warning-dialog"]').waitFor({ state: 'detached', timeout: 5000 });
      } catch {
        // Fallback: dialog might stay in DOM but hidden
        try {
          await page.locator('[data-testid="system-use-warning-dialog"]').waitFor({ state: 'hidden', timeout: 3000 });
        } catch {
          // Dialog may not exist or already dismissed
        }
      }
      
      // CRITICAL: Wait for next step's element to be clickable (not just visible)
      // This ensures the dialog is fully dismissed and not blocking interactions
      try {
        const nextElementId = 'ID_1f0829e2';
        const nextXpath = getXpathById(nextElementId, page.url());
        const nextElement = page.locator(`xpath=${nextXpath}`).nth(0);
        
        // Wait for element to be visible first
        await nextElement.waitFor({ state: 'visible', timeout: 10000 });
        
        // CRITICAL: Wait for element to be clickable (not blocked by dialog)
        // Check if dialog is blocking by trying to click the element
        for (let attempt = 0; attempt < 20; attempt++) {  // Increased attempts (4 seconds max)
          try {
            // Check if dialog still exists and is visible
            const dialogCount = await page.locator('[data-testid="system-use-warning-dialog"]').count();
            if (dialogCount === 0) {
              // Dialog is gone - element should be clickable
              break;
            }
            
            // Check if dialog is visible (might be in DOM but hidden)
            const dialogVisible = await page.locator('[data-testid="system-use-warning-dialog"]').first.isVisible({ timeout: 100 });
            if (!dialogVisible) {
              // Dialog is hidden - element should be clickable
              break;
            }
            
            // Dialog still visible - wait a bit more
            await page.waitForTimeout(200);
          } catch {
            // Dialog check failed - assume it's gone
            break;
          }
        }
        
        // Additional wait to ensure animations complete
        await page.waitForTimeout(500);
        
        console.log(`✅ Dialog dismissed, next element (${nextElementId}) ready`);
      } catch (e: any) {
        console.log(`⚠️  Could not verify next element clickable: ${e}`);
        // Continue anyway - next step will handle its own timeout
      }
      console.log(`✅ Step 2: Clicked Continue (element_id: ${elementId2})`);
      await page.screenshot({ path: 'storage/screenshots/pw_step2_Continue.png' });
    } catch (e: any) {
      try {
        await page.screenshot({ path: 'storage/screenshots/pw_step2_Continue_failed.png' });
        console.log('📸 Screenshot saved: storage/screenshots/pw_step2_Continue_failed.png');
      } catch {
        // Screenshot capture failed, continue anyway
      }
      console.log(`ℹ️  Step 2: Continue not found (optional step): ${e}`);
      // Optional step - continuing without failing test
    }
    
    // Step 3: Click on link Login .(https://hub-stage.datacommons.cancer.gov/)
    await page.waitForTimeout(3000);  // Wait 3 seconds before step
    // Using element_id: ID_1f0829e2 (PURE REGISTRY - XPath from JSON ONLY)
    const elementId3 = 'ID_1f0829e2';
    
    try {
      const xpath3 = getXpathById(elementId3, page.url());  // Lookup from JSON registry (prefers current page registry)
      const selector3 = `xpath=${xpath3}`;
      const element3 = page.locator(selector3).nth(0);
      await element3.waitFor({ state: 'visible', timeout: 10000 });
      await element3.click();
      await page.waitForTimeout(1000);  // Wait after click (matches AI behavior)
      console.log(`✅ Step 3: Clicked Login (element_id: ${elementId3})`);
      await page.screenshot({ path: 'storage/screenshots/pw_step3_Login.png' });
    } catch (e: any) {
      try {
        await page.screenshot({ path: 'storage/screenshots/pw_step3_Login_failed.png' });
        console.log('📸 Screenshot saved: storage/screenshots/pw_step3_Login_failed.png');
      } catch {
        // Screenshot capture failed, continue anyway
      }
      const errorMsg = `Step 3: Failed to click Login (element_id: ${elementId3}): ${e}`;
      console.log(`❌ ${errorMsg}`);
      criticalFailures.push(errorMsg);
      throw new Error(errorMsg);  // Fail fast on critical errors
    }
    
    // Step 4: Click On Login.gov button.
    await page.waitForTimeout(3000);  // Wait 3 seconds before step
    // Using element_id: ID_9f0ca1d2 (PURE REGISTRY - XPath from JSON ONLY)
    const elementId4 = 'ID_9f0ca1d2';
    
    try {
      const xpath4 = getXpathById(elementId4, page.url());  // Lookup from JSON registry (prefers current page registry)
      const selector4 = `xpath=${xpath4}`;
      const element4 = page.locator(selector4).nth(0);
      await element4.waitFor({ state: 'visible', timeout: 10000 });
      await element4.click();
      await page.waitForTimeout(1000);  // Wait after click (matches AI behavior)
      console.log(`✅ Step 4: Clicked Login.gov (element_id: ${elementId4})`);
      await page.screenshot({ path: 'storage/screenshots/pw_step4_Login_gov.png' });
    } catch (e: any) {
      try {
        await page.screenshot({ path: 'storage/screenshots/pw_step4_Login_gov_failed.png' });
        console.log('📸 Screenshot saved: storage/screenshots/pw_step4_Login_gov_failed.png');
      } catch {
        // Screenshot capture failed, continue anyway
      }
      const errorMsg = `Step 4: Failed to click Login.gov (element_id: ${elementId4}): ${e}`;
      console.log(`❌ ${errorMsg}`);
      criticalFailures.push(errorMsg);
      throw new Error(errorMsg);  // Fail fast on critical errors
    }
    
    // Step 5: Enter Username as Laxmi_AI_test@yahoo.com
    await page.waitForTimeout(3000);  // Wait 3 seconds before step
    // Using element_id: ID_038bd7a7 (PURE REGISTRY - XPath from JSON ONLY)
    const elementId5 = 'ID_038bd7a7';
    
    const fillText5 = 'Laxmi_AI_test@yahoo.com';
    
    try {
      const xpath5 = getXpathById(elementId5, page.url());  // Lookup from JSON registry (prefers current page registry)
      const selector5 = `xpath=${xpath5}`;
      const element5 = page.locator(selector5).nth(0);
      await element5.waitFor({ state: 'visible', timeout: 10000 });
      
      // Check if field is readonly/disabled
      const isReadonly5 = await element5.evaluate((el: any) => el.readOnly || el.disabled);
      if (isReadonly5) {
        throw new Error(`Field ${selector5} is readonly or disabled`);
      }
      
      // Fill the field
      await element5.fill(fillText5);
      await page.waitForTimeout(500);  // Wait after fill (matches AI behavior)
      
      // Verify the value was filled correctly
      const actualValue5 = await element5.inputValue();
      if (actualValue5 === fillText5) {
        console.log('✅ Step 5: Filled Username (verified)');
      } else {
        console.log(`⚠️  Step 5: Fill mismatch - expected ${fillText5.substring(0, 20)}..., got ${actualValue5.substring(0, 20)}...`);
      }
      await page.screenshot({ path: 'storage/screenshots/pw_step5_Username.png' });
    } catch (e: any) {
      try {
        await page.screenshot({ path: 'storage/screenshots/pw_step5_Username_failed.png' });
        console.log('📸 Screenshot saved: storage/screenshots/pw_step5_Username_failed.png');
      } catch {
        // Screenshot capture failed, continue anyway
      }
      const errorMsg = `Step 5: Failed to fill Username (element_id: ${elementId5}): ${e}`;
      console.log(`❌ ${errorMsg}`);
      criticalFailures.push(errorMsg);
      throw new Error(errorMsg);  // Fail fast on critical errors
    }
    
    // Step 6: Enter Password as Testnci123456789!
    await page.waitForTimeout(3000);  // Wait 3 seconds before step
    // Using element_id: ID_21bb0a8e (PURE REGISTRY - XPath from JSON ONLY)
    const elementId6 = 'ID_21bb0a8e';
    
    const fillText6 = 'Testnci123456789!';
    
    try {
      const xpath6 = getXpathById(elementId6, page.url());  // Lookup from JSON registry (prefers current page registry)
      const selector6 = `xpath=${xpath6}`;
      const element6 = page.locator(selector6).nth(0);
      await element6.waitFor({ state: 'visible', timeout: 10000 });
      
      // Check if field is readonly/disabled
      const isReadonly6 = await element6.evaluate((el: any) => el.readOnly || el.disabled);
      if (isReadonly6) {
        throw new Error(`Field ${selector6} is readonly or disabled`);
      }
      
      // Fill the field
      await element6.fill(fillText6);
      await page.waitForTimeout(500);  // Wait after fill (matches AI behavior)
      
      // Verify the value was filled correctly
      const actualValue6 = await element6.inputValue();
      if (actualValue6 === fillText6) {
        console.log('✅ Step 6: Filled Password (verified)');
      } else {
        console.log(`⚠️  Step 6: Fill mismatch - expected ${fillText6.substring(0, 20)}..., got ${actualValue6.substring(0, 20)}...`);
      }
      await page.screenshot({ path: 'storage/screenshots/pw_step6_Password.png' });
    } catch (e: any) {
      try {
        await page.screenshot({ path: 'storage/screenshots/pw_step6_Password_failed.png' });
        console.log('📸 Screenshot saved: storage/screenshots/pw_step6_Password_failed.png');
      } catch {
        // Screenshot capture failed, continue anyway
      }
      const errorMsg = `Step 6: Failed to fill Password (element_id: ${elementId6}): ${e}`;
      console.log(`❌ ${errorMsg}`);
      criticalFailures.push(errorMsg);
      throw new Error(errorMsg);  // Fail fast on critical errors
    }
    
    // Step 7: Click Submit Button
    await page.waitForTimeout(3000);  // Wait 3 seconds before step
    // Using element_id: ID_64134b7b (PURE REGISTRY - XPath from JSON ONLY)
    const elementId7 = 'ID_64134b7b';
    
    try {
      const xpath7 = getXpathById(elementId7, page.url());  // Lookup from JSON registry (prefers current page registry)
      const selector7 = `xpath=${xpath7}`;
      const element7 = page.locator(selector7).nth(0);
      await element7.waitFor({ state: 'visible', timeout: 10000 });
      await element7.click();
      await page.waitForTimeout(1000);  // Wait after click (matches AI behavior)
      console.log(`✅ Step 7: Clicked Submit (element_id: ${elementId7})`);
      await page.screenshot({ path: 'storage/screenshots/pw_step7_Submit.png' });
    } catch (e: any) {
      try {
        await page.screenshot({ path: 'storage/screenshots/pw_step7_Submit_failed.png' });
        console.log('📸 Screenshot saved: storage/screenshots/pw_step7_Submit_failed.png');
      } catch {
        // Screenshot capture failed, continue anyway
      }
      const errorMsg = `Step 7: Failed to click Submit (element_id: ${elementId7}): ${e}`;
      console.log(`❌ ${errorMsg}`);
      criticalFailures.push(errorMsg);
      throw new Error(errorMsg);  // Fail fast on critical errors
    }
    
    // Step 8: Enter the TOTP/authenticator code in the one-time code input field. Use browser_fill tool. The TOTP code will be automatically generated by the system.
    await page.waitForTimeout(3000);  // Wait 3 seconds before step
    // Using element_id: ID_5dd5f3e3 (PURE REGISTRY - XPath from JSON ONLY)
    const elementId8 = 'ID_5dd5f3e3';
    
    // TOTP step - generate code dynamically
    // Note: .env file is already loaded at test start (TOTP_SECRET_KEY)
    let fillText8: string;
    try {
      // Try to use otplib for TOTP generation
      let otplib: any;
      try {
        otplib = require('otplib');
      } catch {
        // Auto-install otplib if missing
        const { execSync } = require('child_process');
        console.log('⚠️  otplib not found. Attempting to install...');
        try {
          execSync('npm install otplib', { stdio: 'inherit' });
          otplib = require('otplib');
          console.log('✅ otplib installed successfully');
        } catch (installError: any) {
          throw new Error(`otplib library not installed and auto-install failed. Please install manually with: npm install otplib. Error: ${installError}`);
        }
      }
      
      const secretKey = process.env.TOTP_SECRET_KEY;
      if (!secretKey) {
        throw new Error('TOTP_SECRET_KEY not found in environment variables');
      }
      const totp = otplib.authenticator;
      const totpCode = totp.generate(secretKey);
      console.log(`🔐 Step 8: Generated TOTP code: ${totpCode.substring(0, 2)}****`);
      fillText8 = totpCode;
    } catch (e: any) {
      throw new Error(`Failed to generate TOTP code: ${e}`);
    }
    
    try {
      const xpath8 = getXpathById(elementId8, page.url());  // Lookup from JSON registry (prefers current page registry)
      const selector8 = `xpath=${xpath8}`;
      const element8 = page.locator(selector8).nth(0);
      await element8.waitFor({ state: 'visible', timeout: 10000 });
      
      // Check if field is readonly/disabled
      const isReadonly8 = await element8.evaluate((el: any) => el.readOnly || el.disabled);
      if (isReadonly8) {
        throw new Error(`Field ${selector8} is readonly or disabled`);
      }
      
      // Fill the field
      await element8.fill(fillText8);
      await page.waitForTimeout(500);  // Wait after fill (matches AI behavior)
      
      // Verify the value was filled correctly
      const actualValue8 = await element8.inputValue();
      if (actualValue8 === fillText8) {
        console.log('✅ Step 8: Filled TOTP (verified)');
      } else {
        console.log(`⚠️  Step 8: Fill mismatch - expected ${fillText8.substring(0, 20)}..., got ${actualValue8.substring(0, 20)}...`);
      }
      await page.screenshot({ path: 'storage/screenshots/pw_step8_TOTP.png' });
    } catch (e: any) {
      try {
        await page.screenshot({ path: 'storage/screenshots/pw_step8_TOTP_failed.png' });
        console.log('📸 Screenshot saved: storage/screenshots/pw_step8_TOTP_failed.png');
      } catch {
        // Screenshot capture failed, continue anyway
      }
      const errorMsg = `Step 8: Failed to fill TOTP (element_id: ${elementId8}): ${e}`;
      console.log(`❌ ${errorMsg}`);
      criticalFailures.push(errorMsg);
      throw new Error(errorMsg);  // Fail fast on critical errors
    }
    
    // Step 9: Wait 5 seconds
    await page.waitForTimeout(3000);  // Wait 3 seconds before step
    try {
      await page.waitForTimeout(5000);
      console.log('⏱️  Step 9: Waited 5000ms');
      // Capture screenshot after wait
      try {
        await page.screenshot({ path: 'storage/screenshots/pw_step9_wait.png' });
        console.log('📸 Screenshot saved: storage/screenshots/pw_step9_wait.png');
      } catch {
        // Ignore screenshot errors
      }
    } catch (e: any) {
      console.log(`❌ Step 9: Wait failed: ${e}`);
      // Capture screenshot even on failure
      try {
        await page.screenshot({ path: 'storage/screenshots/pw_step9_wait_failed.png' });
        console.log('📸 Screenshot saved: storage/screenshots/pw_step9_wait_failed.png');
      } catch {
        // Ignore screenshot errors
      }
      // Continuing to next step despite failure (to capture screenshots)
    }
    
    // Step 10: Click Submit button to submit the TOTP code
    await page.waitForTimeout(3000);  // Wait 3 seconds before step
    // Using element_id: ID_64134b7b (PURE REGISTRY - XPath from JSON ONLY)
    const elementId10 = 'ID_64134b7b';
    
    try {
      const xpath10 = getXpathById(elementId10, page.url());  // Lookup from JSON registry (prefers current page registry)
      const selector10 = `xpath=${xpath10}`;
      const element10 = page.locator(selector10).nth(0);
      await element10.waitFor({ state: 'visible', timeout: 10000 });
      await element10.click();
      await page.waitForTimeout(1000);  // Wait after click (matches AI behavior)
      console.log(`✅ Step 10: Clicked Submit (element_id: ${elementId10})`);
      await page.screenshot({ path: 'storage/screenshots/pw_step10_Submit.png' });
    } catch (e: any) {
      try {
        await page.screenshot({ path: 'storage/screenshots/pw_step10_Submit_failed.png' });
        console.log('📸 Screenshot saved: storage/screenshots/pw_step10_Submit_failed.png');
      } catch {
        // Screenshot capture failed, continue anyway
      }
      const errorMsg = `Step 10: Failed to click Submit (element_id: ${elementId10}): ${e}`;
      console.log(`❌ ${errorMsg}`);
      criticalFailures.push(errorMsg);
      throw new Error(errorMsg);  // Fail fast on critical errors
    }
    
    // Step 11: Handle 2FA reminder (if appears)
    // Tool: browser_screenshot (not yet supported in generator)
    
    // Step 12: click on the button with text "Grant"(if appears)
    await page.waitForTimeout(3000);  // Wait 3 seconds before step
    // Using element_id: ID_931e4f32 (PURE REGISTRY - XPath from JSON ONLY)
    const elementId12 = 'ID_931e4f32';
    
    try {
      const xpath12 = getXpathById(elementId12, page.url());  // Lookup from JSON registry (prefers current page registry)
      const selector12 = `xpath=${xpath12}`;
      const element12 = page.locator(selector12).nth(0);
      await element12.waitFor({ state: 'visible', timeout: 10000 });
      await element12.click();
      await page.waitForTimeout(1000);  // Wait after click (matches AI behavior)
      console.log(`✅ Step 12: Clicked Grant (element_id: ${elementId12})`);
      await page.screenshot({ path: 'storage/screenshots/pw_step12_Grant.png' });
    } catch (e: any) {
      try {
        await page.screenshot({ path: 'storage/screenshots/pw_step12_Grant_failed.png' });
        console.log('📸 Screenshot saved: storage/screenshots/pw_step12_Grant_failed.png');
      } catch {
        // Screenshot capture failed, continue anyway
      }
      console.log(`ℹ️  Step 12: Grant not found (optional step): ${e}`);
      // Optional step - continuing without failing test
    }
    
    // Step 13: Verify successful login
    // Tool: browser_screenshot (not yet supported in generator)
    
    // Step 14: click on "Data Submissions" link , it goes to https://hub-stage.datacommons.cancer.gov/data-submissions
    await page.waitForTimeout(3000);  // Wait 3 seconds before step
    // Using element_id: ID_287bf516 (PURE REGISTRY - XPath from JSON ONLY)
    const elementId14 = 'ID_287bf516';
    
    try {
      const xpath14 = getXpathById(elementId14, page.url());  // Lookup from JSON registry (prefers current page registry)
      const selector14 = `xpath=${xpath14}`;
      const element14 = page.locator(selector14).nth(0);
      await element14.waitFor({ state: 'visible', timeout: 10000 });
      await element14.click();
      await page.waitForTimeout(1000);  // Wait after click (matches AI behavior)
      console.log(`✅ Step 14: Clicked Data Submissions (element_id: ${elementId14})`);
      await page.screenshot({ path: 'storage/screenshots/pw_step14_Data_Submissions.png' });
    } catch (e: any) {
      try {
        await page.screenshot({ path: 'storage/screenshots/pw_step14_Data_Submissions_failed.png' });
        console.log('📸 Screenshot saved: storage/screenshots/pw_step14_Data_Submissions_failed.png');
      } catch {
        // Screenshot capture failed, continue anyway
      }
      const errorMsg = `Step 14: Failed to click Data Submissions (element_id: ${elementId14}): ${e}`;
      console.log(`❌ ${errorMsg}`);
      criticalFailures.push(errorMsg);
      throw new Error(errorMsg);  // Fail fast on critical errors
    }
    
    // Step 15: On Data submission page click on button called "Create a Data Submission"
    await page.waitForTimeout(3000);  // Wait 3 seconds before step
    // Using element_id: ID_72bfbac4 (PURE REGISTRY - XPath from JSON ONLY)
    const elementId15 = 'ID_72bfbac4';
    
    try {
      const xpath15 = getXpathById(elementId15, page.url());  // Lookup from JSON registry (prefers current page registry)
      const selector15 = `xpath=${xpath15}`;
      const element15 = page.locator(selector15).nth(0);
      await element15.waitFor({ state: 'visible', timeout: 10000 });
      await element15.click();
      await page.waitForTimeout(1000);  // Wait after click (matches AI behavior)
      console.log(`✅ Step 15: Clicked Create a Data Submission (element_id: ${elementId15})`);
      await page.screenshot({ path: 'storage/screenshots/pw_step15_Create_a_Data_Submission.png' });
    } catch (e: any) {
      try {
        await page.screenshot({ path: 'storage/screenshots/pw_step15_Create_a_Data_Submission_failed.png' });
        console.log('📸 Screenshot saved: storage/screenshots/pw_step15_Create_a_Data_Submission_failed.png');
      } catch {
        // Screenshot capture failed, continue anyway
      }
      const errorMsg = `Step 15: Failed to click Create a Data Submission (element_id: ${elementId15}): ${e}`;
      console.log(`❌ ${errorMsg}`);
      criticalFailures.push(errorMsg);
      throw new Error(errorMsg);  // Fail fast on critical errors
    }
    
    // Check if there were any critical failures
    if (criticalFailures.length > 0) {
      console.log(`\n❌ Test completed with ${criticalFailures.length} critical failure(s):`);
      for (const failure of criticalFailures) {
        console.log(`  - ${failure}`);
      }
      throw new Error(`Test failed: ${criticalFailures.length} critical step(s) failed`);
    } else {
      console.log('✅ Test completed successfully');
    }
  } catch (e: any) {
    console.log(`❌ Test failed: ${e}`);
    // Capture final screenshot even on failure
    try {
      await page.screenshot({ path: 'storage/screenshots/pw_test_final_failed.png' });
      console.log('📸 Final screenshot saved: storage/screenshots/pw_test_final_failed.png');
    } catch {
      // Ignore screenshot errors
    }
    throw e;  // Re-raise to exit with non-zero code
  }
});


