"""
Test script for simple generator
"""
from pathlib import Path
from generator.simple_generator import generate_playwright_script

# Test story
story = """Step 1: Go to https://hub-stage.datacommons.cancer.gov/
Step 1 a: Wait 3 seconds
Step 2: If there is a Continue button click on that.
Step 3: Click on link Login .(https://hub-stage.datacommons.cancer.gov/)
Step 4: Click On Login.gov button.
Step 5: Enter Username as Laxmi_AI_test@yahoo.com
Step 6: Enter Password as Testnci123456789!
Step 7: Click Submit Button
Step 8: Enter the TOTP/authenticator code in the one-time code input field. Use browser_fill tool. The TOTP code will be automatically generated by the system.
Step 9: Wait 5 seconds
Step 10: Click Submit button to submit the TOTP code
Step 11: Handle 2FA reminder (if appears)
Step 12: click on the button with text "Grant"(if appears)
Step 13: Verify successful login
Step 14: click on "Data Submissions" link , it goes to https://hub-stage.datacommons.cancer.gov/data-submissions
Step 15: On Data submission page click on button called "Create a Data Submission"
Step 16: Pick GC from the Datacommons dropdown form the pop pup form.
Step 17: Pick NewTestSpn_laxmi from the Study dropdown from the pop up form.
Step 18:Enter Timestamp in the Submission name text box on the pop up form .
Step 19: Click Create on the pop up form"""

# Generate script
element_maps_dir = Path("element_maps")
output_file = Path("tests/generated/test_simple_generated.py")

result = generate_playwright_script(story, element_maps_dir, output_file)

print("=" * 60)
print("SIMPLE GENERATOR RESULTS")
print("=" * 60)
print(f"Success: {result['success']}")
print(f"Steps processed: {result['steps_processed']}")
print(f"Output file: {result['output_file']}")
print()

if result['missing_elements']:
    print("⚠️  Missing elements:")
    for missing in result['missing_elements']:
        print(f"  Step {missing['step']}: {missing['name']} ({missing['text'][:60]}...)")
else:
    print("✅ All elements found in registry!")

