#!/usr/bin/env python3
"""Extract XPath and URL for each step from generated script"""
import re
import json
from pathlib import Path
from generator.simple_generator import (
    parse_story, detect_action_type, extract_element_name, 
    find_element_in_registries, load_registry_files, extract_url_from_step
)

# Load registries
element_maps_dir = Path("element_maps")
registries = load_registry_files(element_maps_dir)

# Story
story = """Step 1: Go to https://hub-stage.datacommons.cancer.gov/
Step 1 a: Wait 3 seconds
Step 2: If there is a Continue button click on that.
Step 3: Click on link Login .(https://hub-stage.datacommons.cancer.gov/)
Step 4: Click On Login.gov button.
Step 5: Enter Username as Laxmi_AI_test@yahoo.com
Step 6: Enter Password as Testnci123456789!
Step 7: Click Submit Button
Step 8: Enter the TOTP/authenticator code in the one-time code input field. Use browser_fill tool. The TOTP code will be automatically generated by the system.
Step 9: Wait 5 seconds
Step 10: Click Submit button to submit the TOTP code
Step 11: Handle 2FA reminder (if appears)
Step 12: click on the button with text "Grant"(if appears)
Step 13: Verify successful login
Step 14: click on "Data Submissions" link , it goes to https://hub-stage.datacommons.cancer.gov/data-submissions
Step 15: On Data submission page click on button called "Create a Data Submission"
Step 16: Pick GC from the Datacommons dropdown form the pop pup form.
Step 17: Pick NewTestSpn_laxmi from the Study dropdown from the pop up form.
Step 18:Enter Timestamp in the Submission name text box on the pop up form .
Step 19: Click Create on the pop up form"""

steps = parse_story(story)
current_url = None

print("=" * 80)
print("STEP-BY-STEP XPATH AND URL MAPPING")
print("=" * 80)
print()

for step in steps:
    step_num = step['step_number']
    step_text = step['step_text']
    
    action_type = detect_action_type(step_text)
    url = extract_url_from_step(step_text)
    if url:
        current_url = url
    
    print(f"Step {step_num}: {step_text[:70]}")
    print(f"  Action: {action_type}")
    
    if action_type == 'navigate':
        print(f"  URL: {url or current_url}")
        print(f"  XPath: N/A (navigation)")
    elif action_type == 'wait':
        print(f"  URL: {current_url or 'N/A'}")
        print(f"  XPath: N/A (wait step)")
    elif action_type in ['click', 'fill']:
        element_name = extract_element_name(step_text, action_type)
        if element_name:
            element = find_element_in_registries(element_name, registries, current_url)
            if element:
                print(f"  URL: {element.get('url', current_url or 'N/A')}")
                print(f"  XPath: {element.get('xpath', 'N/A')}")
                print(f"  Element Name: {element.get('element_name', 'N/A')}")
            else:
                print(f"  URL: {current_url or 'N/A'}")
                print(f"  XPath: NOT FOUND (element '{element_name}' not in registry)")
        else:
            print(f"  URL: {current_url or 'N/A'}")
            print(f"  XPath: NOT FOUND (could not extract element name)")
    else:
        print(f"  URL: {current_url or 'N/A'}")
        print(f"  XPath: N/A (action type: {action_type})")
    
    print()

