"""
Test script for refactored Agent
"""
import asyncio
import logging
from agent.core.agent import Agent

logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(name)s - %(levelname)s - %(message)s')

story = """Step 1: Go to https://hub-stage.datacommons.cancer.gov/
Step 1 a: Wait 3 seconds
Step 2: If there is a Continue button click on that.
Step 3: Click on the Login button.
Step 4: Click On Login.gov button.
Step 5: Enter Username as Laxmi_AI_test@yahoo.com
Step 6: Enter Password as Testnci123456789!
Step 7: Click Submit Button
Step 8: Enter the TOTP/authenticator code in the one-time code input field. Use browser_fill tool. The TOTP code will be automatically generated by the system.
Step 9: Wait 5 seconds
Step 10: Click Submit button to submit the TOTP code
Step 11: Handle 2FA reminder (if appears)
Step 12: click on the button with text "Grant"(if appears)
Step 13: Verify successful login
Step 14: click on "Data Submissions" link , it goes to https://hub-stage.datacommons.cancer.gov/data-submissions
Step 15: On Data submission page click on button called "Create a Data Submission"
"""

async def main():
    print("="*60)
    print("Testing Refactored Agent")
    print("="*60)
    
    agent = Agent()
    print(f"✅ Agent initialized: {agent.context.execution_id}")
    
    print("\n🚀 Starting story execution...")
    results = await agent.execute_story(story, max_iterations=50)
    
    print("\n" + "="*60)
    print("Execution Results")
    print("="*60)
    print(f"Status: {results.get('status')}")
    print(f"Execution ID: {results.get('execution_id')}")
    print(f"Actions Taken: {len(results.get('actions_taken', []))}")
    print(f"Screenshots: {len(results.get('screenshots', []))}")
    
    if results.get('error'):
        print(f"❌ Error: {results.get('error')}")
    
    if results.get('summary'):
        print(f"Summary: {results.get('summary')}")
    
    print("\n📋 Actions:")
    for i, action in enumerate(results.get('actions_taken', [])[:10], 1):
        print(f"  {i}. {action.get('tool')}: {action.get('result', '')[:100]}")
    
    if len(results.get('actions_taken', [])) > 10:
        print(f"  ... and {len(results.get('actions_taken', [])) - 10} more actions")
    
    return results

if __name__ == '__main__':
    results = asyncio.run(main())





